# silverbullet: The knowledge tinkerer's notebook
# https://github.com/silverbulletmd/silverbullet
# https://silverbullet.md/

services:
  ts-silverbullet:
    image: tailscale/tailscale:v1.76
    container_name: ts-silverbullet
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: sb
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/docker/silverbullet/ts_data:/var/lib/tailscale/
    - /opt/docker/silverbullet/serve-config.json:/config/serve-config.json

  silverbullet:
    image: zefhemel/silverbullet
    container_name: silverbullet
    restart: unless-stopped
    environment:
      SB_USER: "${SB_CREDS}"
    volumes:
    - /opt/docker/silverbullet/space:/space
    network_mode: service:ts-silverbullet

  watchtower:
    image: containrrr/watchtower
    container_name: wt-silverbullet
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
