# silverbullet: The knowledge tinkerer's notebook
# https://github.com/silverbulletmd/silverbullet
# https://silverbullet.md/

services:
  tailscale:
    image: tailscale/tailscale:v1.76
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: sb
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /cephfs/silverbullet/ts_data:/var/lib/tailscale/
    - /cephfs/silverbullet/serve-config.json:/config/serve-config.json
    deploy:
      restart_policy:
        condition: on-failure

  silverbullet:
    image: zefhemel/silverbullet
    environment:
      SB_USER: "${SB_CREDS}"
    volumes:
    - /cephfs/silverbullet/space:/space
    deploy:
      restart_policy:
        condition: on-failure

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: wt-silverbullet
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
