# silverbullet: The knowledge tinkerer's notebook
# https://github.com/silverbulletmd/silverbullet
# https://silverbullet.md/

services:
  silverbullet:
    image: zefhemel/silverbullet
    networks:
    - tailnet
    volumes:
    - /cephfs/silverbullet/space:/space
    environment:
      SB_USER: "${SB_CREDS}"
    healthcheck:
      test: ["CMD", "deno", "eval", "try { await fetch('http://localhost:3000'); Deno.exit(0) } catch { Deno.exit(1) }"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "sb"
      tsdproxy.container_port: 3000
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

networks:
  tailnet:
    external: true

