# Tailscale golink: A private shortlink service for tailnets
# https://github.com/tailscale/golink

services:
  golink:
    image: ghcr.io/tailscale/golink:main
    volumes:
    - '/cephfs/golink/data:/home/nonroot'
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

