services:
  ripe-atlas:
    image: jamesits/ripe-atlas:latest
    restart: always
    environment:
      RXTXRPT: "yes"
    volumes:
    - "/opt/ripe-atlas/etc:/var/atlas-probe/etc"
    - "/opt/ripe-atlas/status:/var/atlas-probe/status"
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETUID
    - SETGID
    - DAC_OVERRIDE
    - NET_RAW
    mem_limit: "64000000000"
    mem_reservation: 64m
    labels:
    - "traefik.enable=false"
    - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
         max-size: 10m

  watchtower:
    image: containrrr/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.docker/config.json:/config.json # enable only if you need it
    command: --cleanup --include-restarting --include-stopped --revive-stopped --label-enable
