# heimdall: An Application dashboard and launcher
# https://github.com/linuxserver/Heimdall

services:
  ts-heimdall:
    image: tailscale/tailscale:latest
    container_name: ts-heimdall
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: heimdall
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/docker/heimdall/ts_data:/var/lib/tailscale/
    - /opt/docker/heimdall/serve-config.json:/config/serve-config.json

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - /opt/docker/heimdall/config:/config
    network_mode: service:ts-heimdall
    restart: unless-stopped
