# heimdall: An Application dashboard and launcher
# https://github.com/linuxserver/Heimdall

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    networks:
    - tailnet
    volumes:
    - /cephfs/heimdall/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "heimdall"
      tsdproxy.container_port: 80
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

networks:
  tailnet:
    external: true

