# it-tools: Collection of handy online tools for developers, with great UX.
# https://github.com/CorentinTh/it-tools

services:
  tools:
    image: corentinth/it-tools:latest
    networks:
    - tailnet
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "tools"
      tsdproxy.container_port: 80
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

networks:
  tailnet:
    external: true

