# vault-unseal: auto-unseal utility for Hashicorp Vault
# https://github.com/lrstanley/vault-unseal

services:
  vault-unseal:
    image: ghcr.io/lrstanley/vault-unseal
    environment:
      ALLOW_SINGLE_NODE: true
      CONFIG_PATH: /etc/vault-unseal.yaml
    volumes:
    - /cephfs/vault-unseal/vault-unseal.yaml:/etc/vault-unseal.yaml
    deploy:
      restart_policy:
        condition: on-failure
