# shepherd: Docker swarm service for automatically updating your services whenever their image is refreshed
# https://github.com/containrrr/shepherd

services:
  shepherd:
    image: containrrr/shepherd
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SLEEP_TIME: "12h"
      TZ: "US/Central"
      IGNORELIST_SERVICES: "label=shepherd.enable=false"
      FILTER_SERVICES: "label=shepherd.enable=true"
    deploy:
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      shepherd.enable: "true"


