# ntfy: Send push notifications to your phone or desktop using PUT/POST
# https://github.com/binwiederhier/ntfy
# https://ntfy.sh/

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
    - serve
    environment:
    - TZ=America/Chicago    # optional: set desired timezone
    volumes:
    - /opt/docker/ntfy/cache/ntfy:/var/cache/ntfy
    - /opt/docker/ntfy/etc/ntfy:/etc/ntfy
    - /opt/docker/ntfy/lib/ntf:/var/lib/ntfy
    ports:
    - 8080:80
    healthcheck: # this needs to be the port inside the container, not the host port
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
