# cyberchef: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis
# https://github.com/gchq/CyberChef

services:
  ts-cyberchef:
    image: tailscale/tailscale:latest
    container_name: ts-cyberchef
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: cyber
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
      - /opt/docker/cyberchef/ts_data:/var/lib/tailscale/
      - /opt/docker/cyberchef/serve-config.json:/config/serve-config.json

  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:latest
    restart: unless-stopped
    network_mode: service:ts-cyberchef
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
