# cyberchef: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis
# https://github.com/gchq/CyberChef

services:
  cyberchef:
    image: mpepping/cyberchef:latest
    networks:
    - tailnet
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "cyber"
      tsdproxy.container_port: 8000
      tsdproxy.ephemeral: "true"

networks:
  tailnet:
    external: true

