services:
  coredns:
    image: coredns/coredns
    command: -conf /data/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "9153:9153/tcp"
    volumes:
      - /cephfs/coredns/:/data:ro
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      shepherd.enable: "false"
