# calibre-web: Web app for browsing, reading and downloading eBooks stored in a Calibre database
# https://github.com/janeczku/calibre-web

services:
  ts-calibre:
    image: tailscale/tailscale:latest
    container_name: ts-calibre
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: calibre
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/docker/calibre-web/ts_data:/var/lib/tailscale/
    - /opt/docker/calibre-web/serve-config.json:/config/serve-config.json

  calibre:
    image: lscr.io/linuxserver/calibre-web:0.6.23
    container_name: calibre-web
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - DOCKER_MODS=linuxserver/mods:universal-calibre
    - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
    - /opt/docker/calibre-web/calibre-config:/config
    - /opt/docker/calibre-web/calibre-library:/books
    network_mode: service:ts-calibre
    restart: unless-stopped
