# calibre-web: Web app for browsing, reading and downloading eBooks stored in a Calibre database
# https://github.com/janeczku/calibre-web

services:
  tailscale:
    image: tailscale/tailscale:v1.76
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: calibre
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /cephfs/calibre-web/ts_data:/var/lib/tailscale/
    - /cephfs/calibre-web/serve-config.json:/config/serve-config.json
    deploy:
      restart_policy:
        condition: on-failure

  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - DOCKER_MODS=linuxserver/mods:universal-calibre
    - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
    - /cephfs/calibre-web/calibre-config:/config
    - /cephfs/calibre-web/calibre-library:/books
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure

