# calibre-web: Web app for browsing, reading and downloading eBooks stored in a Calibre database
# https://github.com/janeczku/calibre-web

services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    networks:
    - tailnet
    volumes:
    - /cephfs/calibre-web/calibre-config:/config
    - /cephfs/calibre-web/calibre-library:/books
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - DOCKER_MODS=linuxserver/mods:universal-calibre
    - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    healthcheck:
      test: curl --fail http://localhost:8083 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "calibre"
      tsdproxy.container_port: 8083
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

networks:
  tailnet:
    external: true

