services:
  golink:
    container_name: golink
    restart: unless-stopped
    image: ghcr.io/tailscale/golink:main
    volumes:
    - '/opt/golink/data:/home/nonroot'
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
