services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: heimdall-tailscale
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: ${TS_HOSTNAME:-ts-docker}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/heimdall/ts_data:/var/lib/tailscale/
    - /opt/heimdall/serve-config.json:/config/serve-config.json

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - /opt/heimdall/config:/config
    network_mode: service:tailscale
    restart: unless-stopped
