# uptime-kuma: A fancy self-hosted monitoring tool
# https://github.com/louislam/uptime-kuma
# https://uptime.kuma.pet/

services:
  ts-uptime:
    image: tailscale/tailscale:latest
    container_name: ts-uptime
    restart: unless-stopped
    ports:
    - 3001:3001
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: uptime
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_STATE_DIR: /var/lib/tailscale/
    volumes:
    - /opt/docker/uptime/ts_data:/var/lib/tailscale/

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime
    restart: unless-stopped
    volumes:
    - /opt/docker/uptime/data:/app/data
    network_mode: service:ts-uptime
