services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: linkding-tailscale
    restart: unless-stopped
    ports:
    - 9090:9090
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: ${TS_HOSTNAME:-ts-docker}
      TS_STATE_DIR: "/var/lib/tailscale/"
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS:-}
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/linkding/ts_data:/var/lib/tailscale/
    - /opt/linkding/serve-config.json:/config/serve-config.json

  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    network_mode: service:tailscale
    volumes:
    - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
    - stack.env
    restart: unless-stopped
