services:
  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    restart: unless-stopped
    command: redis-server --save 30 1 --loglevel warning
    networks:
    - searxng
    volumes:
    - /opt/searxng/redis-data:/data
    cap_drop:
    - ALL
    cap_add:
    - SETGID
    - SETUID
    - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
    - searxng
    ports:
    - "127.0.0.1:8888:8888"
    volumes:
    - /opt/searxng/searxng:/etc/searxng:rw
    environment:
    - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    - BIND_ADDRESS=0.0.0.0:8888
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    ipam:
      driver: default

