# linkding: Self-hosted bookmark manager that is designed be to be minimal, fast, and easy to set up using Docker.
# https://github.com/sissbruecker/linkding
# https://linkding.link/

services:
  linkding:
    image: sissbruecker/linkding:latest
    networks:
    - tailnet
    volumes:
    - /cephfs/linkding/data:/etc/linkding/data
    environment:
      LD_DISABLE_BACKGROUND_TASKS: "False"
      LD_DISABLE_URL_VALIDATION: "False"
      LD_FAVICON_PROVIDER: https://favicon.twenty.com/{domain}/32
      LD_HOST_PORT: 9090
      LD_LOG_X_FORWARDED_FOR: "True"
      LD_SUPERUSER_NAME: ${LD_SUPERUSER_NAME:-admin}
      LD_SUPERUSER_PASSWORD: ${LD_SUPERUSER_PASSWORD:-}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "links"
      tsdproxy.container_port: 9090
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

networks:
  tailnet:
    external: true

