# opengist: Self-hosted pastebin powered by Git, open-source alternative to Github Gist.
# https://github.com/thomiceli/opengist

services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1
    networks:
    - tailnet
    volumes:
    - /cephfs/opengist/data:/opengist
    environment:
      OG_GITHUB_CLIENT_KEY: ${OG_GITHUB_CLIENT_KEY:-}
      OG_GITHUB_SECRET: ${OG_GITHUB_SECRET:-}
      OG_SSH_GIT_ENABLED: "false"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "gist"
      tsdproxy.container_port: 6157
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

networks:
  tailnet:
    external: true

