# opengist: Self-hosted pastebin powered by Git, open-source alternative to Github Gist.
# https://github.com/thomiceli/opengist

services:
  ts-opengist:
    image: tailscale/tailscale:latest
    container_name: ts-opengist
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: gist
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/docker/opengist/ts_data:/var/lib/tailscale/
    - /opt/docker/opengist/serve-config.json:/config/serve-config.json

  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    network_mode: service:ts-opengist
    volumes:
    - /opt/docker/opengist/data:/opengist
    environment:
      OG_GITHUB_CLIENT_KEY: ${OG_GITHUB_CLIENT_KEY:-}
      OG_GITHUB_SECRET: ${OG_GITHUB_SECRET:-}
      OG_SSH_GIT_ENABLED: false
