# opengist: Self-hosted pastebin powered by Git, open-source alternative to Github Gist.
# https://github.com/thomiceli/opengist

services:
  ts-opengist:
    image: tailscale/tailscale:latest
    container_name: ts-opengist
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: gist
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/docker/opengist/ts_data:/var/lib/tailscale/
    - /opt/docker/opengist/serve-config.json:/config/serve-config.json

  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    network_mode: service:ts-opengist
    # ports:
    #   - "6157:6157" # HTTP port
    #   - "2222:2222" # SSH port, can be removed if you don't use SSH
    volumes:
    - "/opt/docker/opengist/data:/opengist"
    environment:
      OG_EXTERNAL_URL: ${OG_EXTERNAL_URL:-}
      OG_GITHUB_CLIENT_KEY: ${OG_GITHUB_CLIENT_KEY:-}
      OG_GITHUB_SECRET: ${OG_GITHUB_SECRET:-}
      OG_SSH_EXTERNAL_DOMAIN: ${OG_SSH_EXTERNAL_DOMAIN:-}
    healthcheck:
      test: curl --fail http://localhost:6157/healthcheck | grep '"database":"ok","opengist":"ok"' || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
