# vault: A tool for secrets management, encryption as a service, and privileged access management
# https://github.com/hashicorp/vault
# https://www.vaultproject.io/

services:
  ts-vault:
    image: tailscale/tailscale:v1.76
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: vault
      TS_STATE_DIR: "/var/lib/tailscale/"
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /cephfs/vault/ts_data:/var/lib/tailscale/
    - /cephfs/vault/serve-config.json:/config/serve-config.json
    deploy:
      restart_policy:
        condition: on-failure

  vault:
    image: hashicorp/vault
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
    cap_add:
    - IPC_LOCK
    volumes:
    - /cephfs/vault/data:/vault/data
    - /cephfs/vault/config:/vault/config
    - /cephfs/vault/log:/vault/log
    command: vault server -config=/vault/config/vault.hcl
    deploy:
      restart_policy:
        condition: on-failure

