# vault: A tool for secrets management, encryption as a service, and privileged access management
# https://github.com/hashicorp/vault
# https://www.vaultproject.io/

services:
  vault:
    image: hashicorp/vault
    command: vault server -config=/vault/config/vault.hcl
    networks:
    - tailnet
    - vault
    volumes:
    - /cephfs/vault/data:/vault/data
    - /cephfs/vault/config:/vault/config
    - /cephfs/vault/log:/vault/log
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
    healthcheck:
      test: wget -q http://127.0.0.1:8200/v1/sys/health -O - || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "vault"
      tsdproxy.container_port: 8200
      tsdproxy.ephemeral: "true"
      shepherd.enable: "true"

  vault-unseal:
    image: ghcr.io/lrstanley/vault-unseal
    networks:
    - vault
    volumes:
    - /cephfs/vault-unseal/vault-unseal.yaml:/etc/vault-unseal.yaml
    environment:
      ALLOW_SINGLE_NODE: "true"
      CONFIG_PATH: "/etc/vault-unseal.yaml"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      shepherd.enable: "true"

networks:
  tailnet:
    external: true
  vault:

