# ripe-atlas: This is the RIPE Atlas software probe packaged as a Docker image.
# https://github.com/Jamesits/docker-ripe-atlas
# https://atlas.ripe.net/docs/howtos/software-probes.html

services:
  ripe-atlas:
    image: jamesits/ripe-atlas:latest
    volumes:
    - "/cephfs/ripe-atlas/etc:/var/atlas-probe/etc"
    - "/cephfs/ripe-atlas/status:/var/atlas-probe/status"
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETUID
    - SETGID
    - DAC_OVERRIDE
    - NET_RAW
    logging:
      driver: json-file
      options:
         max-size: 10m
    environment:
      RXTXRPT: "yes"
    healthcheck:
      test: find /var/atlas-probe/status/ -mmin -5 || exit
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      shepherd.enable: "true"

