# ripe-atlas: This is the RIPE Atlas software probe packaged as a Docker image.
# https://github.com/Jamesits/docker-ripe-atlas
# https://atlas.ripe.net/docs/howtos/software-probes.html

services:
  ripe-atlas:
    image: jamesits/ripe-atlas:latest
    restart: always
    environment:
      RXTXRPT: "yes"
    volumes:
    - "/opt/docker/ripe-atlas/etc:/var/atlas-probe/etc"
    - "/opt/docker/ripe-atlas/status:/var/atlas-probe/status"
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETUID
    - SETGID
    - DAC_OVERRIDE
    - NET_RAW
    mem_limit: "64000000000"
    mem_reservation: 64m
    labels:
    - "traefik.enable=false"
    - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
         max-size: 10m
    healthcheck:
      test: find /var/atlas-probe/status/ -mmin -5 || exit
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s

  watchtower:
    image: containrrr/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.docker/config.json:/config.json # enable only if you need it
    command: --cleanup --include-restarting --include-stopped --revive-stopped --label-enable
