# bearlytics: Privacy-first, no-nonsense web analytics.
# https://github.com/HermanMartinus/bearlytics

services:
  ts-bearlytics:
    image: tailscale/tailscale:v1.78.3
    container_name: ts-bearlytics
    restart: unless-stopped
    ports:
    - 8000:8000
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:?err}
      TS_HOSTNAME: bearlytics
      TS_STATE_DIR: /var/lib/tailscale/
      TS_SERVE_CONFIG: /config/serve-config.json
    volumes:
    - /opt/docker/bearlytics/ts_data:/var/lib/tailscale/
    - /opt/docker/bearlytics/serve-config.json:/config/serve-config.json

  bearlytics:
    image: ghcr.io/hermanmartinus/bearlytics:latest
    network_mode: service:ts-bearlytics
    volumes:
    - /opt/docker/bearlytics/analytics:/app/data
    environment:
      SECRET_KEY: ${SECRET_KEY:?err}
      DB_PATH: ${DB_PATH:-/app/data/analytics.db}
      SALT_SECRET: ${SALT_SECRET:-?err}
      DEBUG: False
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost}
      UID: 1001
      GID: 1001
    restart: unless-stopped

