# tsdproxy: Tailscale Docker Proxy
# https://github.com/almeidapaulopt/tsdproxy

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    networks:
    - tailnet
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /cephfs/tsdproxy/data:/data
    - /cephfs/tsdproxy/config:/config
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      shepherd.enable: "false"

networks:
  tailnet:
    external: true

